//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.11 at 09:35:42 PM WIB 
//


package com.myhost.spring_soap.nasabah_ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.myhost.spring_soap.nasabah_ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.myhost.spring_soap.nasabah_ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRequestNasabahById }
     * 
     */
    public GetRequestNasabahById createGetRequestNasabahById() {
        return new GetRequestNasabahById();
    }

    /**
     * Create an instance of {@link GetResponseNasabahById }
     * 
     */
    public GetResponseNasabahById createGetResponseNasabahById() {
        return new GetResponseNasabahById();
    }

    /**
     * Create an instance of {@link NasabahInfo }
     * 
     */
    public NasabahInfo createNasabahInfo() {
        return new NasabahInfo();
    }

    /**
     * Create an instance of {@link GetResponseNasabahAll }
     * 
     */
    public GetResponseNasabahAll createGetResponseNasabahAll() {
        return new GetResponseNasabahAll();
    }

    /**
     * Create an instance of {@link GetRequestNasabahAll }
     * 
     */
    public GetRequestNasabahAll createGetRequestNasabahAll() {
        return new GetRequestNasabahAll();
    }

    /**
     * Create an instance of {@link AddResponseNasabah }
     * 
     */
    public AddResponseNasabah createAddResponseNasabah() {
        return new AddResponseNasabah();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link DeleteRequestNasabah }
     * 
     */
    public DeleteRequestNasabah createDeleteRequestNasabah() {
        return new DeleteRequestNasabah();
    }

    /**
     * Create an instance of {@link UpdateResponseNasabah }
     * 
     */
    public UpdateResponseNasabah createUpdateResponseNasabah() {
        return new UpdateResponseNasabah();
    }

    /**
     * Create an instance of {@link DeleteResponseNasabah }
     * 
     */
    public DeleteResponseNasabah createDeleteResponseNasabah() {
        return new DeleteResponseNasabah();
    }

    /**
     * Create an instance of {@link UpdateRequestNasabah }
     * 
     */
    public UpdateRequestNasabah createUpdateRequestNasabah() {
        return new UpdateRequestNasabah();
    }

    /**
     * Create an instance of {@link AddRequestNasabah }
     * 
     */
    public AddRequestNasabah createAddRequestNasabah() {
        return new AddRequestNasabah();
    }

}
